name: Docker Publish

on:
  push:
    branches:
      - main

env:
  CONTEXT: .
  IMAGE_TAG: docker.io/lvillis/tcping:latest

jobs:
  job1:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to registry
        uses: docker/login-action@v3.4.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.17.0
        with:
          context: ${{ env.CONTEXT }}
          platforms: linux/amd64
          file: Dockerfile
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_TAG }}
          cache-to: type=inline
          tags: ${{ env.IMAGE_TAG }}
