name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  CONTEXT: .
  GHCR_TAG: ghcr.io/lvillis/tcping:latest
  DOCKER_TAG: docker.io/lvillis/tcping:latest

jobs:
  job1:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0

      - name: Login to docker.io
        uses: docker/login-action@v3.4.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ env.CONTEXT }}
          platforms: linux/amd64
          file: Dockerfile
          push: true
          cache-from: type=registry,ref=${{ env.DOCKER_TAG }}
          cache-to: type=inline
          tags: |
            ${{ env.GHCR_TAG }}
            ${{ env.DOCKER_TAG }}
